os: linux
dist: xenial
language: python

python:
    - "3.6"

install:
    - pip install -r requirements/local.txt

before_script:
    - python manage.py makemigrations --check --dry-run
    - python manage.py migrate
    # - python manage.py collectstatic --noinput

script:
    - black --check --diff .
    - flake8 .
    - coverage run manage.py test

after_success:
    - coveralls

